
version: '3'
services:
  web-ui:
    build:
      context: ./web-ui
    ports:
      - "80:3000"
    container_name: LSD_web-ui
    restart: always
    volumes:
       - ./web-ui:/usr/src/app/web-ui
